import { Result } from "./basic_dropdown/basic_dropdown";

const method_presets =
    [
        "5S-Methode",
        "7 Verschwendungsarten (Muda)",
        "A3-Methode",
        "Ablauforganisation",
        "Agilität",
        "Änderungsmanagement",
        "Aufbauorganisation",
        "Aufwandsschätzung",
        "Behältermanagement",
        "Black Box",
        "Business Process Management",
        "Cashflow-Analyse",
        "Delphi-Methode",
        "DMAIC",
        "Entscheidungsmatrix",
        "Funktionendiagramm",
        "Gesamtanlageneffektivität",
        "Just-in-Time",
        "Kaikaku",
        "Kaizen",
        "KVP – Kontinuierlicher Verbesserungsprozess",
        "Metra-Potenzial-Methode (MPM)",
        "Mura",
        "Muri",
        "Nivellierung / Heijunka",
        "Nutzwertanalyse",
        "PDCA",
        "PERT: Program Evaluation and Review Technique",
        "Risikoanalyse",
        "Risikobewertung",
        "Risikomanagement",
        "SMED – Single Minute Exchange of Die",
        "Theory of Constraints – Engpasstheorie",
        "Total Quality Management (TQM)",
        "TPM – Total Productive Maintenance",
        "Wertstromanalyse/-design",
        "Wertstrommanagement",
        "Workflow Management",
    ] as string[];


export { method_presets }